/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

/**
 *
 * @author Yuki
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
        setTitle("Dashboard");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bexit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        databarang = new javax.swing.JMenuItem();
        JenisBarang = new javax.swing.JMenuItem();
        Distributor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        BarangMasuk = new javax.swing.JMenuItem();
        BarangKeluar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Lapdatabarang = new javax.swing.JMenuItem();
        LapBarangmasuk = new javax.swing.JMenuItem();
        Labarangkeluar = new javax.swing.JMenuItem();
        LapDistributor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 28)); // NOI18N
        jLabel1.setText("SELAMAT DATANG DI APLIKASI");

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel2.setText("PENGELOLAAN  TOKO RAJA BANGUNAN");

        bexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logout.png"))); // NOI18N
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        jMenu1.setText("Master");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        databarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon_Data_Barang-removebg-preview.png"))); // NOI18N
        databarang.setText("Data Barang");
        databarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                databarangActionPerformed(evt);
            }
        });
        jMenu1.add(databarang);

        JenisBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon_Data_Barang-removebg-preview.png"))); // NOI18N
        JenisBarang.setText("Jenis Barang");
        JenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JenisBarangActionPerformed(evt);
            }
        });
        jMenu1.add(JenisBarang);

        Distributor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon_Siswa-removebg-preview.png"))); // NOI18N
        Distributor.setText("Distributor");
        Distributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DistributorActionPerformed(evt);
            }
        });
        jMenu1.add(Distributor);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        BarangMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon_Transaksi-removebg-preview.png"))); // NOI18N
        BarangMasuk.setText("Barang Masuk");
        BarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangMasukActionPerformed(evt);
            }
        });
        jMenu2.add(BarangMasuk);

        BarangKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon_Transaksi-removebg-preview.png"))); // NOI18N
        BarangKeluar.setText("Barang Keluar");
        BarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarangKeluarActionPerformed(evt);
            }
        });
        jMenu2.add(BarangKeluar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        Lapdatabarang.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Lapdatabarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Opened Folder.png"))); // NOI18N
        Lapdatabarang.setText("Data Barang");
        Lapdatabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapdatabarangActionPerformed(evt);
            }
        });
        jMenu3.add(Lapdatabarang);

        LapBarangmasuk.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LapBarangmasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Opened Folder.png"))); // NOI18N
        LapBarangmasuk.setText("Barang Masuk");
        LapBarangmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapBarangmasukActionPerformed(evt);
            }
        });
        jMenu3.add(LapBarangmasuk);

        Labarangkeluar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        Labarangkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Opened Folder.png"))); // NOI18N
        Labarangkeluar.setText("Barang Keluar");
        Labarangkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabarangkeluarActionPerformed(evt);
            }
        });
        jMenu3.add(Labarangkeluar);

        LapDistributor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon_Siswa-removebg-preview.png"))); // NOI18N
        LapDistributor.setText("Data Distributor");
        LapDistributor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapDistributorActionPerformed(evt);
            }
        });
        jMenu3.add(LapDistributor);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108))))
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel2)
                .addGap(0, 91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                .addComponent(bexit, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void databarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_databarangActionPerformed
        // TODO add your handling code here:
        DataBarang mainMenu = new DataBarang();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_databarangActionPerformed

    private void JenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JenisBarangActionPerformed
        // TODO add your handling code here:
        JenisBarang mainMenu = new JenisBarang();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_JenisBarangActionPerformed

    private void DistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DistributorActionPerformed
        // TODO add your handling code here:
         DataDST mainMenu = new DataDST();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_DistributorActionPerformed

    private void BarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangMasukActionPerformed
        // TODO add your handling code here:
        BarangMasuk mainMenu = new BarangMasuk();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BarangMasukActionPerformed

    private void BarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarangKeluarActionPerformed
        // TODO add your handling code here:
        BarangKeluar mainMenu = new BarangKeluar();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BarangKeluarActionPerformed

    private void LapBarangmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapBarangmasukActionPerformed
        // TODO add your handling code here:
         LapBarangmasuk mainMenu = new LapBarangmasuk();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LapBarangmasukActionPerformed

    private void LapdatabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapdatabarangActionPerformed
        // TODO add your handling code here:
        LapDataBarang mainMenu = new LapDataBarang();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LapdatabarangActionPerformed

    private void LapDistributorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapDistributorActionPerformed
        // TODO add your handling code here:
        LapDataDST mainMenu = new LapDataDST();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LapDistributorActionPerformed

    private void LabarangkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabarangkeluarActionPerformed
        // TODO add your handling code here:
        LapBarangKeluar mainMenu = new LapBarangKeluar();
        mainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabarangkeluarActionPerformed

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BarangKeluar;
    private javax.swing.JMenuItem BarangMasuk;
    private javax.swing.JMenuItem Distributor;
    private javax.swing.JMenuItem JenisBarang;
    private javax.swing.JMenuItem Labarangkeluar;
    private javax.swing.JMenuItem LapBarangmasuk;
    private javax.swing.JMenuItem LapDistributor;
    private javax.swing.JMenuItem Lapdatabarang;
    private javax.swing.JButton bexit;
    private javax.swing.JMenuItem databarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
